/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bank;

import javax.swing.JFrame;

public class CardBack extends javax.swing.JFrame {

    private Account user;
    
    /**
     * Creates new form CardBack
     */
    public CardBack() {
        setTitle("Card Back");
        initComponents();
    }
    
    /**
     * Creates new form CardBack with user details
     * 
     * @param user The account object representing the user
     */
    public CardBack(Account user) {
        setTitle("Card Back");
        this.user=user;
        initComponents();
        Wand.setCustomIcon(this);
        Wand.setCustomCursor(this);
        displayCardNumber();// Display the CVV number on the card
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cVVBackground = new javax.swing.JPanel();
        CVV = new javax.swing.JLabel();
        decor = new javax.swing.JLabel();
        black = new javax.swing.JPanel();
        phoneNumber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        cardFront = new javax.swing.JToggleButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 320));
        getContentPane().setLayout(null);

        cVVBackground.setLayout(null);

        CVV.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        CVV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CVV.setText("000");
        cVVBackground.add(CVV);
        CVV.setBounds(276, 0, 53, 60);

        decor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dot.jpg"))); // NOI18N
        cVVBackground.add(decor);
        decor.setBounds(0, 0, 340, 60);

        getContentPane().add(cVVBackground);
        cVVBackground.setBounds(20, 90, 340, 60);

        black.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout blackLayout = new javax.swing.GroupLayout(black);
        black.setLayout(blackLayout);
        blackLayout.setHorizontalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        blackLayout.setVerticalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(black);
        black.setBounds(0, 30, 620, 50);

        phoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumber.setText("Tele-E-Gringotts 018 7777358");
        getContentPane().add(phoneNumber);
        phoneNumber.setBounds(10, 10, 190, 16);

        jLabel1.setText("Authorized Signature Not Valid Unless Signed");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 160, 240, 16);

        jLabel2.setText("This card is issued by E-Gringotts pursuant to license by Mastercard Hogwarts Pte.Ltd. ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 180, 470, 16);

        jLabel3.setText("The usage of this card is governed by the Terms & conditions of E-Gringotts Debit Card-i");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 200, 480, 16);

        jLabel4.setText("Agreement. If found, kindly return to the nearest branch. IMPORTANT: PLEASE NOTIFY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 220, 480, 16);

        jLabel7.setText("E-GRINGOTTS CARD CENTRE BEFORE TRAVELLING ABOARD and/ or MAKING");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 240, 440, 16);

        jLabel6.setText("CARD NOT PRESENT PURCHASE.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 260, 240, 16);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo50x50.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(30, 170, 60, 50);

        cardFront.setBackground(new java.awt.Color(51, 51, 51));
        cardFront.setText("<");
        cardFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardFrontActionPerformed(evt);
            }
        });
        getContentPane().add(cardFront);
        cardFront.setBounds(20, 240, 80, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 620, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action event for the card front button click
     * 
     * @param evt The action event
     */
    private void cardFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardFrontActionPerformed
        // Create a new CardFront frame and display it
        CardFront cardFront = new CardFront(user);
        cardFront.setVisible(true);
        cardFront.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_cardFrontActionPerformed

    /**
     * Displays the CVV number of the user's debit card
     */
    public void displayCardNumber() {
         // Set the CVV text field with the CVV number from the user's debit card
        CVV.setText(String.valueOf(user.getDebitCard().getCVV()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardBack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CVV;
    private javax.swing.JLabel background;
    private javax.swing.JPanel black;
    private javax.swing.JPanel cVVBackground;
    private javax.swing.JToggleButton cardFront;
    private javax.swing.JLabel decor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel phoneNumber;
    // End of variables declaration//GEN-END:variables
}
