/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bank;

import javax.swing.JFrame;

public class CardFront extends javax.swing.JFrame {

    private Account user;// Account object representing the user
    
    /**
     * Creates new form CardFront
     */
    public CardFront() {
        setTitle("Card Front");
        initComponents();
    }

    /**
     * Creates new form CardFront with user details
     * 
     * @param user The account object representing the user
     */
    public CardFront(Account user) {
        setTitle("Card Front");
        this.user=user;
        initComponents();
        Wand.setCustomIcon(this);
        Wand.setCustomCursor(this);
        displayCardNumber();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emv = new javax.swing.JLabel();
        debit = new javax.swing.JLabel();
        bankName = new javax.swing.JLabel();
        CardNum = new javax.swing.JLabel();
        valid1 = new javax.swing.JLabel();
        valid2 = new javax.swing.JLabel();
        expiryDate = new javax.swing.JLabel();
        cardBack = new javax.swing.JToggleButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 320));
        getContentPane().setLayout(null);

        emv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emv.png"))); // NOI18N
        getContentPane().add(emv);
        emv.setBounds(60, 100, 70, 50);

        debit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        debit.setText("debit");
        getContentPane().add(debit);
        debit.setBounds(510, 20, 50, 25);

        bankName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logooo1.png"))); // NOI18N
        getContentPane().add(bankName);
        bankName.setBounds(10, 10, 260, 70);

        CardNum.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        CardNum.setForeground(new java.awt.Color(229, 210, 171));
        Card card = new Card();
        CardNum.setText(String.valueOf(card.getCardNum()));
        getContentPane().add(CardNum);
        CardNum.setBounds(60, 170, 510, 40);

        valid1.setForeground(new java.awt.Color(255, 255, 255));
        valid1.setText("THRU");
        getContentPane().add(valid1);
        valid1.setBounds(214, 250, 50, 16);

        valid2.setForeground(new java.awt.Color(255, 255, 255));
        valid2.setText("VALID");
        getContentPane().add(valid2);
        valid2.setBounds(214, 230, 50, 16);

        expiryDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        expiryDate.setForeground(new java.awt.Color(229, 210, 171));
        expiryDate.setText(String.valueOf(card.getExpiryDate()));
        getContentPane().add(expiryDate);
        expiryDate.setBounds(280, 230, 130, 30);

        cardBack.setBackground(new java.awt.Color(51, 51, 51));
        cardBack.setText(">");
        cardBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardBackActionPerformed(evt);
            }
        });
        getContentPane().add(cardBack);
        cardBack.setBounds(515, 243, 80, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/card.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 620, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action event for the card back button click
     * 
     * @param evt The action event
     */
    private void cardBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardBackActionPerformed
        CardBack cardBack = new CardBack(user);
        cardBack.setVisible(true);
        cardBack.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_cardBackActionPerformed

    /**
     * Displays the card number and expiry date of the user's debit card
     */
    public void displayCardNumber() {
        CardNum.setText(user.getDebitCard().getCardNum());
        expiryDate.setText(String.valueOf(user.getDebitCard().getExpiryDate()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardFront().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardNum;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bankName;
    private javax.swing.JToggleButton cardBack;
    private javax.swing.JLabel debit;
    private javax.swing.JLabel emv;
    private javax.swing.JLabel expiryDate;
    private javax.swing.JLabel valid1;
    private javax.swing.JLabel valid2;
    // End of variables declaration//GEN-END:variables
}
