/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bank;

import Admin.AdminProfile;
import static Bank.SignUpPage.isValidDate;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class EditProfile extends javax.swing.JFrame {
    private Account user;
    /**
     * Creates new form SignUpPage
     */
    public EditProfile() {
        setTitle("Edit Profile");
        initComponents();
    }

    public EditProfile(Account user) {
        setTitle("Edit Profile");
        this.user=user;
        initComponents();
        Wand.setCustomIcon(this);
        Wand.setCustomCursor(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EditProfileTitle = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Usernamefield = new javax.swing.JTextField();
        dob = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        Telephone = new javax.swing.JLabel();
        Telephonefield = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        Emailfield = new javax.swing.JTextField();
        Mailing = new javax.swing.JLabel();
        Mailingfield = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 65, 57));

        EditProfileTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        EditProfileTitle.setForeground(new java.awt.Color(255, 255, 255));
        EditProfileTitle.setText("Edit Profile");

        Username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");

        Usernamefield.setBackground(new java.awt.Color(197, 179, 134));
        Usernamefield.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Usernamefield.setForeground(new java.awt.Color(0, 0, 0));

        dob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        dob.setText("Date of Birth");

        dobField.setBackground(new java.awt.Color(197, 179, 134));
        dobField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dobField.setForeground(new java.awt.Color(0, 0, 0));

        Telephone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Telephone.setForeground(new java.awt.Color(255, 255, 255));
        Telephone.setText("Phone number");

        Telephonefield.setBackground(new java.awt.Color(197, 179, 134));
        Telephonefield.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Telephonefield.setForeground(new java.awt.Color(0, 0, 0));

        Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email address");

        Emailfield.setBackground(new java.awt.Color(197, 179, 134));
        Emailfield.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Emailfield.setForeground(new java.awt.Color(0, 0, 0));

        Mailing.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mailing.setForeground(new java.awt.Color(255, 255, 255));
        Mailing.setText("Mailing home address:");

        Mailingfield.setBackground(new java.awt.Color(197, 179, 134));
        Mailingfield.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Mailingfield.setForeground(new java.awt.Color(0, 0, 0));

        backButton.setBackground(new java.awt.Color(197, 179, 134));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        doneButton.setBackground(new java.awt.Color(197, 179, 134));
        doneButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doneButton.setText("Done");
        doneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/test1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EditProfileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Mailing, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Mailingfield, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telephone))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telephonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditProfileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username)
                    .addComponent(Usernamefield))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob)
                    .addComponent(dobField))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Telephonefield)
                    .addComponent(Telephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Emailfield))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mailing)
                    .addComponent(Mailingfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        String userType = user.getUser().getUserType();
        if(userType.equals("Goblin")){
            AdminProfile adminProfile=new AdminProfile(user);
            adminProfile.setUser(); 
            adminProfile.setUserType(userType);
            adminProfile.setVisible(true);
            adminProfile.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            this.dispose();
        }else{
            UserProfile userProfile = new UserProfile(user);
            userProfile.setUser(); 
            userProfile.setUserType(userType);
            userProfile.setVisible(true);
            userProfile.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt){
        Connection connection = null;
        PreparedStatement statement = null;
        List<String> errors = new ArrayList<>();
        String userid, finduserid,selectquery, updatequery,username,dob,phone,email,address;
        String oldUsername;
        int notFound = 0;
        username=Usernamefield.getText();
        dob=dobField.getText();
        phone=Telephonefield.getText();
        email=Emailfield.getText();
        address=Mailingfield.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Egringotts", "root", "password");
            userid=user.getUserID();
            
            if (username.isEmpty() || dob.isEmpty() || phone.isEmpty() || email.isEmpty() || address.isEmpty() ) {
                errors.add("All the credentials must be filled!");
            }else{
                // Validate date of birth format
                if (!isValidDate(dob)) {
                    errors.add("Invalid date of birth format or invalid date. Please use YYYY-MM-DD format.");
                } 

                if (!phone.matches("\\d+")) {
                    errors.add("Telephone must contain only digits.");
                }

                // Check for existing username
                PreparedStatement statement1 = connection.prepareStatement("SELECT * FROM Account WHERE Username = ? AND UserID <> ?");
                statement1.setString(1, username); // Set the username parameter
                statement1.setString(2, userid); // Set the specific user ID parameter
                ResultSet resultSetUsername = statement1.executeQuery();
                if (resultSetUsername.next()) {
                    // Username exists for another user
                    errors.add("This username already exists for another user!");
                }

                // Validate email format
                if (!email.contains("@")) {
                    errors.add("Invalid email format.");
                }

                if(username.contains(" ")){
                    errors.add("Username cannot contains space.");
                }
            }
          
            // Show all errors at once if any exist
            if (!errors.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), String.join("\n", errors), "Error", JOptionPane.ERROR_MESSAGE);
                return;  // Stop further processing
            }
            
        
            selectquery = "SELECT * FROM Account WHERE UserID= ?";
            updatequery = "UPDATE Account SET Username = ?, Telephone = ?, Email = ?, Address = ?, DOB = ? WHERE UserID=?";
                    
            PreparedStatement selectStatement = connection.prepareStatement(selectquery);
            selectStatement.setString(1, userid);
            ResultSet resultset = selectStatement.executeQuery();
                    
            while (resultset.next()) {
                finduserid=resultset.getString("UserID");
                notFound = 1;

                if (notFound == 1 ) {
                    PreparedStatement updateStatement = connection.prepareStatement(updatequery);
                    updateStatement.setString(1, username);
                    updateStatement.setString(2, phone);
                    updateStatement.setString(3, email);
                    updateStatement.setString(4, address);
                    updateStatement.setString(5, dob);
                    updateStatement.setString(6, userid);
                    updateStatement.executeUpdate();
                    updateStatement.close();
                    JOptionPane.showMessageDialog(new JFrame(), "Profile change successfully!");
                    
                    user.setUsername(username);
                    user.setTelephone(phone);
                    user.setDOB(dob);
                    user.setEmail(email);
                    user.setAddress(address);
                    
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Profile change unsuccessfully!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (notFound == 0) {
                JOptionPane.showMessageDialog(new JFrame(), "User not found!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch (Exception e) {
            System.out.println("Error!" + e.getMessage());
        }
    }
    
    public void setUser() {      
        this.Usernamefield.setText(user.getUsername());
        this.dobField.setText(user.getDOB());
        this.Telephonefield.setText(user.getTelephone());
        this.Emailfield.setText(user.getEmail());
        this.Mailingfield.setText(user.getAddress());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EditProfileTitle;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Emailfield;
    private javax.swing.JLabel Mailing;
    private javax.swing.JTextField Mailingfield;
    private javax.swing.JLabel Telephone;
    private javax.swing.JTextField Telephonefield;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField Usernamefield;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField dobField;
    private javax.swing.JButton doneButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel picture;
    // End of variables declaration//GEN-END:variables
}
