/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Currency;

import Bank.Account;
import Bank.Wand;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class ShowAccountBalance extends javax.swing.JFrame {

    private Account user;

    /**
     * Creates new form ShowAccountBalance
     */
    public ShowAccountBalance() {
        setTitle("Show Account Balance");
        initComponents();
    }

    public ShowAccountBalance(Account user) {
        setTitle("Show Account Balance");
        this.user = user;
        initComponents();
        Wand.setCustomIcon(this);
        Wand.setCustomCursor(this);
        displayUserData();
    }

    public void setUserId() {
        Userid.setText(user.getUserID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        selectedTable = new rojeru_san.complementos.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        UseridLabel = new javax.swing.JLabel();
        Userid = new javax.swing.JLabel();
        BackgroundPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        selectedTable.setBackground(new java.awt.Color(255, 255, 153));
        selectedTable.setForeground(new java.awt.Color(0, 0, 0));
        selectedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Currency", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        selectedTable.setAltoHead(35);
        selectedTable.setColorBackgoundHead(new java.awt.Color(244, 198, 107));
        selectedTable.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        selectedTable.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        selectedTable.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        selectedTable.setColorSelBackgound(new java.awt.Color(255, 153, 153));
        selectedTable.setFuenteFilas(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        selectedTable.setFuenteFilasSelect(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        selectedTable.setFuenteHead(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        selectedTable.setGridColor(new java.awt.Color(0, 0, 0));
        selectedTable.setRowHeight(30);
        jScrollPane1.setViewportView(selectedTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 130, 470, 320);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel1.setLayout(null);

        UseridLabel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        UseridLabel.setForeground(new java.awt.Color(255, 255, 255));
        UseridLabel.setText("UserID:");
        jPanel1.add(UseridLabel);
        UseridLabel.setBounds(20, 10, 80, 40);

        Userid.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        Userid.setForeground(new java.awt.Color(255, 255, 204));
        Userid.setText("user");
        jPanel1.add(Userid);
        Userid.setBounds(110, 10, 240, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 40, 470, 60);

        BackgroundPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flying.jpg"))); // NOI18N
        getContentPane().add(BackgroundPic);
        BackgroundPic.setBounds(0, 0, 600, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Fetch and display the user's balance data in the table
    private void displayUserData() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Egringotts", "root", "password");

            // Get the UserID of the current user
            String userID = user.getUserID(); // Assuming user is an instance of your User class

            // Create a statement
            Statement statement = connection.createStatement();

            // Execute the query to get data for the specified user
            ResultSet resultSet = statement.executeQuery("SELECT * FROM userbalance WHERE UserID = '" + userID + "'");

            // Get the metadata to determine the number of columns
            ResultSetMetaData metaData = resultSet.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Clear existing rows in the table
            DefaultTableModel model = (DefaultTableModel) selectedTable.getModel();
            model.setRowCount(0);

            // Populate data rows into the table
            while (resultSet.next()) {
                for (int i = 2; i <= columnCount; i++) { // Start from 2 to skip UserID column
                    String columnName = metaData.getColumnName(i);
                    Object columnValue = resultSet.getObject(i);
                    model.addRow(new Object[]{columnName, columnValue}); // Add each column value as a row
                }
            }

            // Close the resources
            resultSet.close();
            statement.close();
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowAccountBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowAccountBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowAccountBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowAccountBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowAccountBalance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundPic;
    private javax.swing.JLabel Userid;
    private javax.swing.JLabel UseridLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro selectedTable;
    // End of variables declaration//GEN-END:variables
}
