/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Bank.*;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * JFrame class representing the Admin Profile window.
 * This window displays the profile information of the admin user.
 */
public class AdminProfile extends javax.swing.JFrame {
    private Account user;
    private String imagePathString;
    /**
     * Creates new form AdminProfile
     */
    
    /**
     * Default constructor for the AdminProfile class.
     * Initializes the window title and GUI components.
     */
    public AdminProfile() {
        setTitle("Admin Profile");
        initComponents();
    }

    /**
     * Constructor for the AdminProfile class that accepts an Account object.
     * Initializes the window title, sets the user object, initializes GUI components,
     * and sets custom icon and cursor.
     * @param user The admin user object.
     */
    public AdminProfile(Account user) {
        setTitle("Admin Profile");
        this.user = user;
        initComponents();
        Wand.setCustomIcon(this);
        Wand.setCustomCursor(this);
        panelMouseEffect.registerMouseEffect();// Register mouse effect for panel
    }

    /**
     * Method to set user information in the UI components.
     * Retrieves user data from the Account object and sets it in corresponding fields.
     */
    public void setUser() {
        this.nameOfUser.setText(user.getUsername());
        this.userID.setText(user.getUserID());
        this.DOB.setText(user.getDOB());
        this.phoneNumber.setText(user.getTelephone());
        this.email.setText(user.getEmail());
        this.homeAddress.setText(user.getAddress());
        
        // Check if the user has a custom avatar image
        if (user.getUserAvatar() != null && user.getUserAvatar().getImagePath() != null && 
            !user.getUserAvatar().getImagePath().trim().equals("/Images/profilePic.jpg")) {
            this.imagePathString = user.getUserAvatar().getImagePath();
            profilePic.setIcon(new javax.swing.ImageIcon(this.imagePathString));
        } else {
            System.out.println("Please wait for the image path to parse in....");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMouseEffect = new Bank.PanelMouseEffect();
        top = new javax.swing.JPanel();
        myProfile = new java.awt.Label();
        logo = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        Home = new java.awt.Button();
        Profile = new java.awt.Button();
        functionButtonsPanel = new javax.swing.JPanel();
        showDailyTransaction = new javax.swing.JToggleButton();
        currencyManagement = new javax.swing.JToggleButton();
        numberOfUsers = new javax.swing.JToggleButton();
        editAnnouncement = new javax.swing.JToggleButton();
        UserIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editAnnIcon = new javax.swing.JLabel();
        profilePicBackground = new javax.swing.JPanel();
        nameOfUser = new javax.swing.JLabel();
        userTypes = new javax.swing.JLabel();
        profilePic = new javax.swing.JLabel();
        changeProfilePic = new javax.swing.JToggleButton();
        userID = new javax.swing.JLabel();
        changePasswordButton = new javax.swing.JToggleButton();
        changePINButton = new javax.swing.JToggleButton();
        editProfileButton = new javax.swing.JToggleButton();
        phoneNumberBackground = new javax.swing.JPanel();
        phoneNumber = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        emailBackground = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        homeAddressBackground = new javax.swing.JPanel();
        homeAddress = new javax.swing.JLabel();
        homeAdressLabel = new javax.swing.JLabel();
        usernameBackground1 = new javax.swing.JPanel();
        DOB = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 600));
        getContentPane().setLayout(null);

        top.setBackground(new java.awt.Color(77, 59, 49));

        myProfile.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        myProfile.setForeground(new java.awt.Color(255, 255, 255));
        myProfile.setText("My Profile");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo100x100.png"))); // NOI18N

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addComponent(logo)
                .addGap(21, 21, 21)
                .addComponent(myProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(502, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelMouseEffect.add(top);
        top.setBounds(0, 0, 1070, 100);

        bottom.setBackground(new java.awt.Color(77, 59, 49));

        Home.setBackground(new java.awt.Color(77, 59, 49));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setLabel("Home");
        Home.setPreferredSize(new java.awt.Dimension(55, 25));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Profile.setBackground(new java.awt.Color(77, 59, 49));
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Profile.setForeground(new java.awt.Color(255, 255, 255));
        Profile.setLabel("Me");
        Profile.setPreferredSize(new java.awt.Dimension(55, 25));
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Profile, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelMouseEffect.add(bottom);
        bottom.setBounds(0, 520, 1070, 80);

        functionButtonsPanel.setBackground(new java.awt.Color(255, 255, 255,100));
        functionButtonsPanel.setForeground(new java.awt.Color(255, 255, 255));

        showDailyTransaction.setBackground(new java.awt.Color(214, 177, 120));
        showDailyTransaction.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        showDailyTransaction.setText("Show Daily Transaction");
        showDailyTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showDailyTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDailyTransactionActionPerformed(evt);
            }
        });

        currencyManagement.setBackground(new java.awt.Color(214, 177, 120));
        currencyManagement.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        currencyManagement.setText("Currency management");
        currencyManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        currencyManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyManagementActionPerformed(evt);
            }
        });

        numberOfUsers.setBackground(new java.awt.Color(214, 177, 120));
        numberOfUsers.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        numberOfUsers.setText("Display Number Of Users");
        numberOfUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberOfUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfUsersActionPerformed(evt);
            }
        });

        editAnnouncement.setBackground(new java.awt.Color(214, 177, 120));
        editAnnouncement.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        editAnnouncement.setText("Edit Announcement");
        editAnnouncement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editAnnouncement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAnnouncementActionPerformed(evt);
            }
        });

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserIcon.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transactionIcon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/curManageIcon.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        editAnnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editAnnIcon.png"))); // NOI18N

        javax.swing.GroupLayout functionButtonsPanelLayout = new javax.swing.GroupLayout(functionButtonsPanel);
        functionButtonsPanel.setLayout(functionButtonsPanelLayout);
        functionButtonsPanelLayout.setHorizontalGroup(
            functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionButtonsPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberOfUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showDailyTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAnnIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currencyManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        functionButtonsPanelLayout.setVerticalGroup(
            functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionButtonsPanelLayout.createSequentialGroup()
                .addGroup(functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(functionButtonsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showDailyTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currencyManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(functionButtonsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(functionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberOfUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAnnIcon)
                    .addComponent(editAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIcon))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelMouseEffect.add(functionButtonsPanel);
        functionButtonsPanel.setBounds(370, 120, 650, 180);

        profilePicBackground.setBackground(new java.awt.Color(255, 255, 255, 80));
        profilePicBackground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nameOfUser.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        nameOfUser.setForeground(new java.awt.Color(255, 255, 255));
        nameOfUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameOfUser.setText("Admin");

        userTypes.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        userTypes.setForeground(new java.awt.Color(204, 204, 204));
        userTypes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userTypes.setText("Goblin");

        profilePic.setBackground(new java.awt.Color(102, 255, 255));
        profilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profilePic.jpg"))); // NOI18N

        changeProfilePic.setBackground(new java.awt.Color(163, 151, 135));
        changeProfilePic.setText("Change Profile Picture");
        changeProfilePic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeProfilePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeProfilePicActionPerformed(evt);
            }
        });

        userID.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        userID.setForeground(new java.awt.Color(255, 255, 255));
        userID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userID.setText("userID");

        changePasswordButton.setBackground(new java.awt.Color(213, 210, 175));
        changePasswordButton.setText("Change Password");
        changePasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        changePINButton.setBackground(new java.awt.Color(213, 210, 175));
        changePINButton.setText("Change PIN");
        changePINButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePINButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePINButtonActionPerformed(evt);
            }
        });

        editProfileButton.setBackground(new java.awt.Color(163, 151, 135));
        editProfileButton.setText("Edit Profile");
        editProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePicBackgroundLayout = new javax.swing.GroupLayout(profilePicBackground);
        profilePicBackground.setLayout(profilePicBackgroundLayout);
        profilePicBackgroundLayout.setHorizontalGroup(
            profilePicBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userTypes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nameOfUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePicBackgroundLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(profilePicBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePicBackgroundLayout.createSequentialGroup()
                        .addComponent(profilePic)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePicBackgroundLayout.createSequentialGroup()
                        .addComponent(changeProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePicBackgroundLayout.createSequentialGroup()
                        .addGroup(profilePicBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changePINButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );
        profilePicBackgroundLayout.setVerticalGroup(
            profilePicBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePicBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeProfilePic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTypes)
                .addGap(1, 1, 1)
                .addComponent(editProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePINButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelMouseEffect.add(profilePicBackground);
        profilePicBackground.setBounds(60, 120, 250, 380);

        phoneNumberBackground.setBackground(new java.awt.Color(255, 255, 255, 100));
        phoneNumberBackground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        phoneNumber.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumber.setText("018-7777358");

        phoneNumberLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel.setText("Phone Number");

        javax.swing.GroupLayout phoneNumberBackgroundLayout = new javax.swing.GroupLayout(phoneNumberBackground);
        phoneNumberBackground.setLayout(phoneNumberBackgroundLayout);
        phoneNumberBackgroundLayout.setHorizontalGroup(
            phoneNumberBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneNumberBackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(phoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        phoneNumberBackgroundLayout.setVerticalGroup(
            phoneNumberBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneNumberBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(phoneNumberBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumber)
                    .addComponent(phoneNumberLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMouseEffect.add(phoneNumberBackground);
        phoneNumberBackground.setBounds(370, 360, 650, 40);

        emailBackground.setBackground(new java.awt.Color(255, 255, 255, 80));
        emailBackground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        email.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("egringotts@gmail.com");

        emailLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email Address");

        javax.swing.GroupLayout emailBackgroundLayout = new javax.swing.GroupLayout(emailBackground);
        emailBackground.setLayout(emailBackgroundLayout);
        emailBackgroundLayout.setHorizontalGroup(
            emailBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailBackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(emailLabel)
                .addGap(63, 63, 63)
                .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        emailBackgroundLayout.setVerticalGroup(
            emailBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(emailBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMouseEffect.add(emailBackground);
        emailBackground.setBounds(370, 410, 650, 40);

        homeAddressBackground.setBackground(new java.awt.Color(255, 255, 255, 80));
        homeAddressBackground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        homeAddress.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        homeAddress.setForeground(new java.awt.Color(255, 255, 255));
        homeAddress.setText("Magical Land");

        homeAdressLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        homeAdressLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeAdressLabel.setText("Home Address");

        javax.swing.GroupLayout homeAddressBackgroundLayout = new javax.swing.GroupLayout(homeAddressBackground);
        homeAddressBackground.setLayout(homeAddressBackgroundLayout);
        homeAddressBackgroundLayout.setHorizontalGroup(
            homeAddressBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddressBackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(homeAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(homeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeAddressBackgroundLayout.setVerticalGroup(
            homeAddressBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddressBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homeAddressBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeAddress)
                    .addComponent(homeAdressLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMouseEffect.add(homeAddressBackground);
        homeAddressBackground.setBounds(370, 460, 650, 40);

        usernameBackground1.setBackground(new java.awt.Color(255, 255, 255, 80));
        usernameBackground1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        DOB.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        DOB.setForeground(new java.awt.Color(255, 255, 255));
        DOB.setText("01/ 01/2004");

        DOBLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        DOBLabel.setForeground(new java.awt.Color(255, 255, 255));
        DOBLabel.setText("Date of Birth");

        javax.swing.GroupLayout usernameBackground1Layout = new javax.swing.GroupLayout(usernameBackground1);
        usernameBackground1.setLayout(usernameBackground1Layout);
        usernameBackground1Layout.setHorizontalGroup(
            usernameBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernameBackground1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(DOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        usernameBackground1Layout.setVerticalGroup(
            usernameBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernameBackground1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(usernameBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOB)
                    .addComponent(DOBLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMouseEffect.add(usernameBackground1);
        usernameBackground1.setBounds(370, 310, 650, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminProfile.jpg"))); // NOI18N
        panelMouseEffect.add(background);
        background.setBounds(0, 0, 1070, 600);

        getContentPane().add(panelMouseEffect);
        panelMouseEffect.setBounds(0, 0, 1070, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action performed when the "Home" button is clicked.
     * Creates a new instance of UserHomePage, passing the current user as a parameter,
     * sets it visible, disposes the current window.
     * @param evt The action event.
     */
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // Create a new instance of UserHomePage, passing the current user as a parameter
        UserHomePage userHomePage = new UserHomePage(user);
        userHomePage.setUser();
        userHomePage.setUserTypes();
        userHomePage.setVisible(true);
        userHomePage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * Action performed when the "Profile" button is clicked.
     * @param evt The action event.
     */
    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed

    }//GEN-LAST:event_ProfileActionPerformed

    /**
     * Action performed when the "Change Profile Picture" button is clicked.
     * @param evt The action event.
     */
    private void changeProfilePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeProfilePicActionPerformed
        // Call the method to open the file explorer and change the profile picture
        System.out.println(OpenFileViaExplorer(profilePic));
    }//GEN-LAST:event_changeProfilePicActionPerformed

    /**
     * Opens a file explorer and selects a profile picture.
     * @param profilePic The JLabel to set the selected profile picture.
     * @return True if the file was successfully selected, otherwise false.
     */
    private boolean OpenFileViaExplorer(JLabel profilePic) {
        try {
            // Create a file chooser
            JFileChooser fileChooser = new JFileChooser();
            // Set file filter to only show image files
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", "png", "jpg");
            fileChooser.setFileFilter(filter);
            // Set the current directory to the working directory
            fileChooser.setCurrentDirectory(new File("."));
            // Show the open dialog and get the user's action
            int result = fileChooser.showOpenDialog(null);
            System.out.println("Result" + result);
            
            // Check if the user approved the file selection
            if (result == JFileChooser.APPROVE_OPTION) {
                // Get the selected file
                File selectedFile = new File(fileChooser.getSelectedFile().getAbsolutePath());
                System.out.println("Filepath: " + selectedFile);
                
                String selectedfilepath=selectedFile.getAbsolutePath();
                // Create an ImageIcon from the selected file
                ImageIcon icon = new ImageIcon(selectedfilepath);

                // Set the ImageIcon as the icon for the profilePic component
                profilePic.setIcon(icon);
                // Update the user's avatar image path
                user.setUserAvatar(new UserAvatar(selectedfilepath,user.getUserID()));
                System.out.println("the path is:" +user.getUserAvatar().getImagePath());
                Connection connection = null;
                PreparedStatement selectStatement = null;
                ResultSet resultset=null;
                
                String userid, selectquery, updatequery,finduserid,oldImagePath;
                int notFound = 0;
                
                try {
                    // Load the MySQL JDBC driver
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    // Establish a connection to the database
                    connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Egringotts", "root", "password");

                    userid=user.getUserID();
                    selectquery = "SELECT * FROM Account WHERE UserID= ?";
                    updatequery = "UPDATE Account SET ImagePath=? WHERE UserID=?";
                    
                    // Prepare and execute the select query
                    selectStatement = connection.prepareStatement(selectquery);
                    selectStatement.setString(1, userid);
                    resultset = selectStatement.executeQuery();
                    
                    while (resultset.next()) {
                        finduserid=resultset.getString("UserID");
                        oldImagePath = resultset.getString("ImagePath");
                        notFound = 1;

                        // Check if the user was found and update the profile picture path
                        if (notFound == 1 ) {
                            PreparedStatement updateStatement = connection.prepareStatement(updatequery);
                            updateStatement.setString(1, selectedfilepath);
                            updateStatement.setString(2, userid);
                            updateStatement.executeUpdate();
                            updateStatement.close();
                            // Show a success message
                            JOptionPane.showMessageDialog(new JFrame(), "Profile Picture change successfully!");

                        } else {
                            // Show an error message if the update failed
                            JOptionPane.showMessageDialog(new JFrame(), "Profile Picture change unsuccessfully!", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    // Show an error message if the user was not found
                    if (notFound == 0) {
                        JOptionPane.showMessageDialog(new JFrame(), "User not found!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }catch (Exception e) {
                    System.out.println("Error!" + e.getMessage());
                } finally {
                    try {
                        // Close the result set, statement, and connection
                       if (resultset != null) {
                           resultset.close();
                       }
                       if (selectStatement != null) {
                           selectStatement.close();
                       }
                       if (connection != null) {
                           connection.close();
                       }
                   } catch (SQLException e) {
                       System.out.println("Error closing resources: " + e.getMessage());
                   }
                }
                
                // Check if the Desktop class is supported
                if (!Desktop.isDesktopSupported()) {
                    System.out.println("Not supported");
                    return false;
                } else {
                    // Open the selected file
                    Desktop desktop = Desktop.getDesktop();
                    desktop.open(selectedFile);
                    return true;
                }
            } else if (result == JFileChooser.CANCEL_OPTION) {
                // Handle the case when the user cancels the file selection
                System.out.println("Cancelled.");
                return false;
            }
        } catch (IOException e) {
            // Print the stack trace if an IOException occurs
            e.printStackTrace();
            return false;
        }
        return false;
    }
    
    /**
     * Action performed when the "Number of Users" button is clicked.
     * @param evt The action event.
     */
    private void numberOfUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfUsersActionPerformed
        // Open the "Number of Users" window
        NumOfUsers numOfUsers = new NumOfUsers(user);
        // Set the window visibility and close operation
        numOfUsers.setVisible(true);
        numOfUsers.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // Close the current window
        this.dispose();
    }//GEN-LAST:event_numberOfUsersActionPerformed

    /**
     * Action performed when the "Edit Announcement" button is clicked.
     * @param evt The action event.
     */
    private void editAnnouncementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAnnouncementActionPerformed
        EditAnnouncement editAnnouncement = new EditAnnouncement(user);
        editAnnouncement.setVisible(true);
        editAnnouncement.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_editAnnouncementActionPerformed

    /**
     * Action performed when the "Change Password" button is clicked.
     * @param evt The action event.
     */
    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        ChangePassword changePassword = new ChangePassword(user);
        changePassword.setVisible(true);
        changePassword.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    /**
     * Action performed when the "Change PIN" button is clicked.
     * @param evt The action event.
     */
    private void changePINButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePINButtonActionPerformed
        ChangePIN changePIN = new ChangePIN(user);
        changePIN.setVisible(true);
        changePIN.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_changePINButtonActionPerformed

    /**
     * Action performed when the "Edit Profile" button is clicked.
     * @param evt The action event.
     */
    private void editProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileButtonActionPerformed
        EditProfile editProfile = new EditProfile(user);
        editProfile.setUser();
        editProfile.setVisible(true);
        editProfile.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_editProfileButtonActionPerformed

    /**
     * Action performed when the "Show Daily Transaction" button is clicked.
     * @param evt The action event.
     */
    private void showDailyTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDailyTransactionActionPerformed
        TransactionPerDay dailytransaction = new TransactionPerDay(user);
        dailytransaction.setVisible(true);
        dailytransaction.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_showDailyTransactionActionPerformed

    /**
     * Action performed when the "Currency Management" button is clicked.
     * @param evt The action event.
     */
    private void currencyManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyManagementActionPerformed
        CurrencyManagement currency = new CurrencyManagement(user);
        currency.setVisible(true);
        currency.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_currencyManagementActionPerformed

    /**
     * Sets the user type label.
     * @param userType The user type to set.
     */
    public void setUserType(String userType) {
        userTypes.setText(userType);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel DOBLabel;
    private java.awt.Button Home;
    private java.awt.Button Profile;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel background;
    private javax.swing.JPanel bottom;
    private javax.swing.JToggleButton changePINButton;
    private javax.swing.JToggleButton changePasswordButton;
    private javax.swing.JToggleButton changeProfilePic;
    private javax.swing.JToggleButton currencyManagement;
    private javax.swing.JLabel editAnnIcon;
    private javax.swing.JToggleButton editAnnouncement;
    private javax.swing.JToggleButton editProfileButton;
    private javax.swing.JLabel email;
    private javax.swing.JPanel emailBackground;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel functionButtonsPanel;
    private javax.swing.JLabel homeAddress;
    private javax.swing.JPanel homeAddressBackground;
    private javax.swing.JLabel homeAdressLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logo;
    private java.awt.Label myProfile;
    private javax.swing.JLabel nameOfUser;
    private javax.swing.JToggleButton numberOfUsers;
    private Bank.PanelMouseEffect panelMouseEffect;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JPanel phoneNumberBackground;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel profilePic;
    private javax.swing.JPanel profilePicBackground;
    private javax.swing.JToggleButton showDailyTransaction;
    private javax.swing.JPanel top;
    private javax.swing.JLabel userID;
    private javax.swing.JLabel userTypes;
    private javax.swing.JPanel usernameBackground1;
    // End of variables declaration//GEN-END:variables

}
